### ISSUE TITLE
Eldorito.exe Entry Point Not Found

### ISSUE THREAD

**Issue by Yangjo** [DEElekgolo/ElDorito#12]
I have this constant error that pops up and I would have to constantly click ok in order to get it out of view. The text in the error box states, "The procedure entry point GetAdaptersAddresses could not be located in the dynamic link library IPHLPAPI.DLL.
I've had this issue ever since the first release of the eldorito.
I used to click the OK button a number of times until it stopped popping up, now I no longer can do so.
Is this an issue I could solve?
I saw a very similar issue someone else had, is this related to that?

**Comment by emoose** [comment]
Yeah this is the same problem as #10 , join us on IRC and we'll help you out.
