### ISSUE TITLE
No solution file?

### ISSUE THREAD

**Issue by JakeShirley** [DEElekgolo/ElDorito#4]
It seems there is only a filters file for some reason, so building is... uh... well you know.

**Comment by DEElekgolo** [comment]
I added a solution file. Thing is I have some post-build stuff that automatically puts the compiled dll into my Halo Online directory. 
![image](https://cloud.githubusercontent.com/assets/644247/6884428/f021791c-d5a6-11e4-80b6-31817e54941f.png)
Be sure to edit the post-build event so it puts it into your folder
